name = "superplace"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "out"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "superplace-db"
database_id = "8c106540-21b4-4fa9-8879-c4956e459ca1"
